### ISSUE TITLE
BlynkSimpleEsp32.h ?

### ISSUE THREAD

**Issue by def1149** [HocJ2me/ESP32-RTOS-Blynk#1]
BlynkSimpleEsp32.h seems to be missing from the code

**Comment by HocJ2me** [comment]
Hi, maybe you hadn't installed Blynk library.
Solution
Open Arduino IDE
Go to File > Preference
Copy this > [https://dl.espressif.com/dl/package_esp32_index.json 503](https://dl.espressif.com/dl/package_esp32_index.json)
Paste it at the box (besides Additional Boards Manager)
Go to Tools > Board > Boards Manager > search “esp32” by Espressif Systems > Install
Go to Sketch > Include Library > Manage Libraries
Search “Blynk” by Volodymyr Shymanskyy > Install
I prefer that you restart your Arduino IDE
Go to Tools > Board > Your ESP32 Board Type (usually Esp32 Dev Module)
You’re done.

Then, you can try Blynk example.

Go to File > Example > Blynk > Boards_WiFi > Esp32_WiFi
You can see #include <BlynkSimpleEsp32.h>
